name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  push:  
    
jobs:
  executar_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v2

      - name: Instala o Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5

- name: Instala o poetry
        uses: Gr1N/setup-poetry@v4

      - name: Instala as dependências
        run: poetry install
